/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`test/node.js TAP basic instantiation > just a lone root node 1`] = `
Node {
  "children": Map {},
  "dev": true,
  "devOptional": true,
  "edgesIn": Set {},
  "edgesOut": Map {},
  "error": undefined,
  "extraneous": true,
  "inBundle": false,
  "location": "/",
  "name": "root",
  "optional": true,
  "package": Object {
    "name": "root",
  },
  "path": ".",
  "realpath": "/home/user/projects/root",
}
`

exports[`test/node.js TAP testing with dep tree > add new meta under prod 1`] = `
Node {
  "children": Map {
    "prod" => Node {
      "children": Map {
        "meta" => Node {
          "children": Map {
            "metameta" => Node {
              "children": Map {},
              "dev": true,
              "devOptional": true,
              "edgesIn": Set {},
              "edgesOut": Map {},
              "error": undefined,
              "extraneous": true,
              "inBundle": false,
              "location": "/prod/meta/metameta",
              "name": "metameta",
              "optional": true,
              "package": Object {
                "name": "metameta",
                "version": "1.2.3",
              },
              "path": "./node_modules/prod/node_modules/meta/node_modules/metameta",
              "realpath": "/home/user/projects/root/node_modules/prod/node_modules/meta/node_modules/metameta",
              "target": Node {
                "children": Map {},
                "dev": true,
                "devOptional": true,
                "edgesIn": Set {
                  Edge {},
                },
                "edgesOut": Map {
                  "bundled" => Edge {},
                },
                "error": undefined,
                "extraneous": true,
                "inBundle": false,
                "location": "/meta",
                "name": "meta",
                "optional": true,
                "package": Object {
                  "dependencies": Object {
                    "bundled": "",
                  },
                  "devDependencies": Object {
                    "missing": "",
                  },
                  "name": "meta",
                  "version": "1.2.3",
                },
                "path": "./node_modules/meta",
                "realpath": "/home/user/projects/root/node_modules/meta",
              },
            },
          },
          "dev": true,
          "devOptional": true,
          "edgesIn": Set {
            Edge {},
          },
          "edgesOut": Map {},
          "error": undefined,
          "extraneous": true,
          "inBundle": false,
          "location": "/prod/meta",
          "name": "meta",
          "optional": true,
          "package": Object {
            "name": "meta",
            "version": "2.3.4",
          },
          "path": "./node_modules/prod/node_modules/meta",
          "realpath": "/home/user/projects/root/node_modules/prod/node_modules/meta",
        },
      },
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {
        "meta" => Edge {},
        "peer" => Edge {},
      },
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/prod",
      "name": "prod",
      "optional": true,
      "package": Object {
        "dependencies": Object {
          "meta": "",
        },
        "name": "prod",
        "peerDependencies": Object {
          "peer": "",
        },
        "version": "1.2.3",
      },
      "path": "./node_modules/prod",
      "realpath": "/home/user/projects/root/node_modules/prod",
    },
    "bundled" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
        Edge {},
      },
      "edgesOut": Map {
        "meta" => Edge {},
      },
      "error": undefined,
      "extraneous": true,
      "inBundle": true,
      "location": "/bundled",
      "name": "bundled",
      "optional": true,
      "package": Object {
        "dependencies": Object {
          "meta": "",
        },
        "name": "bundled",
        "version": "1.2.3",
      },
      "path": "./node_modules/bundled",
      "realpath": "/home/user/projects/root/node_modules/bundled",
    },
    "dev" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/dev",
      "name": "dev",
      "optional": true,
      "package": Object {
        "name": "dev",
        "version": "1.2.3",
      },
      "path": "./node_modules/dev",
      "realpath": "/home/user/projects/root/node_modules/dev",
    },
    "optional" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/optional",
      "name": "optional",
      "optional": true,
      "package": Object {
        "name": "optional",
        "version": "1.2.3",
      },
      "path": "./node_modules/optional",
      "realpath": "/home/user/projects/root/node_modules/optional",
    },
    "peer" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/peer",
      "name": "peer",
      "optional": true,
      "package": Object {
        "name": "peer",
        "version": "1.2.3",
      },
      "path": "./node_modules/peer",
      "realpath": "/home/user/projects/root/node_modules/peer",
    },
    "extraneous" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {},
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/extraneous",
      "name": "extraneous",
      "optional": true,
      "package": Object {
        "name": "extraneous",
        "version": "1.2.3",
      },
      "path": "./node_modules/extraneous",
      "realpath": "/home/user/projects/root/node_modules/extraneous",
    },
    "meta" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {
        "bundled" => Edge {},
      },
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/meta",
      "name": "meta",
      "optional": true,
      "package": Object {
        "dependencies": Object {
          "bundled": "",
        },
        "devDependencies": Object {
          "missing": "",
        },
        "name": "meta",
        "version": "1.2.3",
      },
      "path": "./node_modules/meta",
      "realpath": "/home/user/projects/root/node_modules/meta",
    },
  },
  "dev": true,
  "devOptional": true,
  "edgesIn": Set {},
  "edgesOut": Map {
    "optional" => Edge {},
    "overlap" => Edge {},
    "optMissing" => Edge {},
    "prod" => Edge {},
    "bundled" => Edge {},
    "missing" => Edge {},
    "dev" => Edge {},
  },
  "error": undefined,
  "extraneous": true,
  "inBundle": false,
  "location": "/",
  "name": "root",
  "optional": true,
  "package": Object {
    "bundleDependencies": Array [
      "bundled",
    ],
    "dependencies": Object {
      "bundled": "",
      "missing": "",
      "prod": "",
    },
    "devDependencies": Object {
      "dev": "",
      "overlap": "",
    },
    "name": "root",
    "optionalDependencies": Object {
      "optional": "",
      "optMissing": "",
      "overlap": "",
    },
  },
  "path": ".",
  "realpath": "/home/user/projects/root",
}
`

exports[`test/node.js TAP testing with dep tree > initial load with some deps 1`] = `
Node {
  "children": Map {
    "prod" => Node {
      "children": Map {
        "meta" => Node {
          "children": Map {},
          "dev": true,
          "devOptional": true,
          "edgesIn": Set {
            Edge {},
          },
          "edgesOut": Map {
            "bundled" => Edge {},
          },
          "error": undefined,
          "extraneous": true,
          "inBundle": false,
          "location": "/prod/meta",
          "name": "meta",
          "optional": true,
          "package": Object {
            "dependencies": Object {
              "bundled": "",
            },
            "devDependencies": Object {
              "missing": "",
            },
            "name": "meta",
            "version": "1.2.3",
          },
          "path": "./node_modules/prod/node_modules/meta",
          "realpath": "/home/user/projects/root/node_modules/prod/node_modules/meta",
        },
      },
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {
        "meta" => Edge {},
        "peer" => Edge {},
      },
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/prod",
      "name": "prod",
      "optional": true,
      "package": Object {
        "dependencies": Object {
          "meta": "",
        },
        "name": "prod",
        "peerDependencies": Object {
          "peer": "",
        },
        "version": "1.2.3",
      },
      "path": "./node_modules/prod",
      "realpath": "/home/user/projects/root/node_modules/prod",
    },
    "bundled" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
        Edge {},
      },
      "edgesOut": Map {
        "meta" => Edge {},
      },
      "error": undefined,
      "extraneous": true,
      "inBundle": true,
      "location": "/bundled",
      "name": "bundled",
      "optional": true,
      "package": Object {
        "dependencies": Object {
          "meta": "",
        },
        "name": "bundled",
        "version": "1.2.3",
      },
      "path": "./node_modules/bundled",
      "realpath": "/home/user/projects/root/node_modules/bundled",
    },
    "dev" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/dev",
      "name": "dev",
      "optional": true,
      "package": Object {
        "name": "dev",
        "version": "1.2.3",
      },
      "path": "./node_modules/dev",
      "realpath": "/home/user/projects/root/node_modules/dev",
    },
    "optional" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/optional",
      "name": "optional",
      "optional": true,
      "package": Object {
        "name": "optional",
        "version": "1.2.3",
      },
      "path": "./node_modules/optional",
      "realpath": "/home/user/projects/root/node_modules/optional",
    },
    "peer" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/peer",
      "name": "peer",
      "optional": true,
      "package": Object {
        "name": "peer",
        "version": "1.2.3",
      },
      "path": "./node_modules/peer",
      "realpath": "/home/user/projects/root/node_modules/peer",
    },
    "extraneous" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {},
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/extraneous",
      "name": "extraneous",
      "optional": true,
      "package": Object {
        "name": "extraneous",
        "version": "1.2.3",
      },
      "path": "./node_modules/extraneous",
      "realpath": "/home/user/projects/root/node_modules/extraneous",
    },
  },
  "dev": true,
  "devOptional": true,
  "edgesIn": Set {},
  "edgesOut": Map {
    "optional" => Edge {},
    "overlap" => Edge {},
    "optMissing" => Edge {},
    "prod" => Edge {},
    "bundled" => Edge {},
    "missing" => Edge {},
    "dev" => Edge {},
  },
  "error": undefined,
  "extraneous": true,
  "inBundle": false,
  "location": "/",
  "name": "root",
  "optional": true,
  "package": Object {
    "bundleDependencies": Array [
      "bundled",
    ],
    "dependencies": Object {
      "bundled": "",
      "missing": "",
      "prod": "",
    },
    "devDependencies": Object {
      "dev": "",
      "overlap": "",
    },
    "name": "root",
    "optionalDependencies": Object {
      "optional": "",
      "optMissing": "",
      "overlap": "",
    },
  },
  "path": ".",
  "realpath": "/home/user/projects/root",
}
`

exports[`test/node.js TAP testing with dep tree > move meta to top level, update stuff 1`] = `
Node {
  "children": Map {
    "prod" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {
        "meta" => Edge {},
        "peer" => Edge {},
      },
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/prod",
      "name": "prod",
      "optional": true,
      "package": Object {
        "dependencies": Object {
          "meta": "",
        },
        "name": "prod",
        "peerDependencies": Object {
          "peer": "",
        },
        "version": "1.2.3",
      },
      "path": "./node_modules/prod",
      "realpath": "/home/user/projects/root/node_modules/prod",
    },
    "bundled" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
        Edge {},
      },
      "edgesOut": Map {
        "meta" => Edge {},
      },
      "error": undefined,
      "extraneous": true,
      "inBundle": true,
      "location": "/bundled",
      "name": "bundled",
      "optional": true,
      "package": Object {
        "dependencies": Object {
          "meta": "",
        },
        "name": "bundled",
        "version": "1.2.3",
      },
      "path": "./node_modules/bundled",
      "realpath": "/home/user/projects/root/node_modules/bundled",
    },
    "dev" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/dev",
      "name": "dev",
      "optional": true,
      "package": Object {
        "name": "dev",
        "version": "1.2.3",
      },
      "path": "./node_modules/dev",
      "realpath": "/home/user/projects/root/node_modules/dev",
    },
    "optional" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/optional",
      "name": "optional",
      "optional": true,
      "package": Object {
        "name": "optional",
        "version": "1.2.3",
      },
      "path": "./node_modules/optional",
      "realpath": "/home/user/projects/root/node_modules/optional",
    },
    "peer" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/peer",
      "name": "peer",
      "optional": true,
      "package": Object {
        "name": "peer",
        "version": "1.2.3",
      },
      "path": "./node_modules/peer",
      "realpath": "/home/user/projects/root/node_modules/peer",
    },
    "extraneous" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {},
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/extraneous",
      "name": "extraneous",
      "optional": true,
      "package": Object {
        "name": "extraneous",
        "version": "1.2.3",
      },
      "path": "./node_modules/extraneous",
      "realpath": "/home/user/projects/root/node_modules/extraneous",
    },
    "meta" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
        Edge {},
      },
      "edgesOut": Map {
        "bundled" => Edge {},
      },
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/meta",
      "name": "meta",
      "optional": true,
      "package": Object {
        "dependencies": Object {
          "bundled": "",
        },
        "devDependencies": Object {
          "missing": "",
        },
        "name": "meta",
        "version": "1.2.3",
      },
      "path": "./node_modules/meta",
      "realpath": "/home/user/projects/root/node_modules/meta",
    },
  },
  "dev": true,
  "devOptional": true,
  "edgesIn": Set {},
  "edgesOut": Map {
    "optional" => Edge {},
    "overlap" => Edge {},
    "optMissing" => Edge {},
    "prod" => Edge {},
    "bundled" => Edge {},
    "missing" => Edge {},
    "dev" => Edge {},
  },
  "error": undefined,
  "extraneous": true,
  "inBundle": false,
  "location": "/",
  "name": "root",
  "optional": true,
  "package": Object {
    "bundleDependencies": Array [
      "bundled",
    ],
    "dependencies": Object {
      "bundled": "",
      "missing": "",
      "prod": "",
    },
    "devDependencies": Object {
      "dev": "",
      "overlap": "",
    },
    "name": "root",
    "optionalDependencies": Object {
      "optional": "",
      "optMissing": "",
      "overlap": "",
    },
  },
  "path": ".",
  "realpath": "/home/user/projects/root",
}
`

exports[`test/node.js TAP testing with dep tree > move new meta to top level 1`] = `
Node {
  "children": Map {
    "prod" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {
        "meta" => Edge {},
        "peer" => Edge {},
      },
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/prod",
      "name": "prod",
      "optional": true,
      "package": Object {
        "dependencies": Object {
          "meta": "",
        },
        "name": "prod",
        "peerDependencies": Object {
          "peer": "",
        },
        "version": "1.2.3",
      },
      "path": "./node_modules/prod",
      "realpath": "/home/user/projects/root/node_modules/prod",
    },
    "bundled" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {
        "meta" => Edge {},
      },
      "error": undefined,
      "extraneous": true,
      "inBundle": true,
      "location": "/bundled",
      "name": "bundled",
      "optional": true,
      "package": Object {
        "dependencies": Object {
          "meta": "",
        },
        "name": "bundled",
        "version": "1.2.3",
      },
      "path": "./node_modules/bundled",
      "realpath": "/home/user/projects/root/node_modules/bundled",
    },
    "dev" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/dev",
      "name": "dev",
      "optional": true,
      "package": Object {
        "name": "dev",
        "version": "1.2.3",
      },
      "path": "./node_modules/dev",
      "realpath": "/home/user/projects/root/node_modules/dev",
    },
    "optional" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/optional",
      "name": "optional",
      "optional": true,
      "package": Object {
        "name": "optional",
        "version": "1.2.3",
      },
      "path": "./node_modules/optional",
      "realpath": "/home/user/projects/root/node_modules/optional",
    },
    "peer" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/peer",
      "name": "peer",
      "optional": true,
      "package": Object {
        "name": "peer",
        "version": "1.2.3",
      },
      "path": "./node_modules/peer",
      "realpath": "/home/user/projects/root/node_modules/peer",
    },
    "extraneous" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {},
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/extraneous",
      "name": "extraneous",
      "optional": true,
      "package": Object {
        "name": "extraneous",
        "version": "1.2.3",
      },
      "path": "./node_modules/extraneous",
      "realpath": "/home/user/projects/root/node_modules/extraneous",
    },
    "meta" => Node {
      "children": Map {
        "metameta" => Node {
          "children": Map {},
          "dev": true,
          "devOptional": true,
          "edgesIn": Set {},
          "edgesOut": Map {},
          "error": undefined,
          "extraneous": true,
          "inBundle": false,
          "location": "/meta/metameta",
          "name": "metameta",
          "optional": true,
          "package": Object {
            "name": "metameta",
            "version": "1.2.3",
          },
          "path": "./node_modules/meta/node_modules/metameta",
          "realpath": "/home/user/projects/root/node_modules/prod/node_modules/meta/node_modules/metameta",
          "target": Node {
            "children": Map {},
            "dev": true,
            "devOptional": true,
            "edgesIn": Set {},
            "edgesOut": Map {
              "bundled" => Edge {},
            },
            "error": undefined,
            "extraneous": true,
            "inBundle": false,
            "location": "/",
            "name": "meta",
            "optional": true,
            "package": Object {
              "dependencies": Object {
                "bundled": "",
              },
              "devDependencies": Object {
                "missing": "",
              },
              "name": "meta",
              "version": "1.2.3",
            },
            "path": "./node_modules/meta",
            "realpath": "/home/user/projects/root/node_modules/meta",
          },
        },
      },
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/meta",
      "name": "meta",
      "optional": true,
      "package": Object {
        "name": "meta",
        "version": "2.3.4",
      },
      "path": "./node_modules/meta",
      "realpath": "/home/user/projects/root/node_modules/meta",
    },
  },
  "dev": true,
  "devOptional": true,
  "edgesIn": Set {},
  "edgesOut": Map {
    "optional" => Edge {},
    "overlap" => Edge {},
    "optMissing" => Edge {},
    "prod" => Edge {},
    "bundled" => Edge {},
    "missing" => Edge {},
    "dev" => Edge {},
  },
  "error": undefined,
  "extraneous": true,
  "inBundle": false,
  "location": "/",
  "name": "root",
  "optional": true,
  "package": Object {
    "bundleDependencies": Array [
      "bundled",
    ],
    "dependencies": Object {
      "bundled": "",
      "missing": "",
      "prod": "",
    },
    "devDependencies": Object {
      "dev": "",
      "overlap": "",
    },
    "name": "root",
    "optionalDependencies": Object {
      "optional": "",
      "optMissing": "",
      "overlap": "",
    },
  },
  "path": ".",
  "realpath": "/home/user/projects/root",
}
`

exports[`test/node.js TAP testing with dep tree > move new meta to top level second time (no-op) 1`] = `
Node {
  "children": Map {
    "prod" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {
        "meta" => Edge {},
        "peer" => Edge {},
      },
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/prod",
      "name": "prod",
      "optional": true,
      "package": Object {
        "dependencies": Object {
          "meta": "",
        },
        "name": "prod",
        "peerDependencies": Object {
          "peer": "",
        },
        "version": "1.2.3",
      },
      "path": "./node_modules/prod",
      "realpath": "/home/user/projects/root/node_modules/prod",
    },
    "bundled" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {
        "meta" => Edge {},
      },
      "error": undefined,
      "extraneous": true,
      "inBundle": true,
      "location": "/bundled",
      "name": "bundled",
      "optional": true,
      "package": Object {
        "dependencies": Object {
          "meta": "",
        },
        "name": "bundled",
        "version": "1.2.3",
      },
      "path": "./node_modules/bundled",
      "realpath": "/home/user/projects/root/node_modules/bundled",
    },
    "dev" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/dev",
      "name": "dev",
      "optional": true,
      "package": Object {
        "name": "dev",
        "version": "1.2.3",
      },
      "path": "./node_modules/dev",
      "realpath": "/home/user/projects/root/node_modules/dev",
    },
    "optional" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/optional",
      "name": "optional",
      "optional": true,
      "package": Object {
        "name": "optional",
        "version": "1.2.3",
      },
      "path": "./node_modules/optional",
      "realpath": "/home/user/projects/root/node_modules/optional",
    },
    "peer" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/peer",
      "name": "peer",
      "optional": true,
      "package": Object {
        "name": "peer",
        "version": "1.2.3",
      },
      "path": "./node_modules/peer",
      "realpath": "/home/user/projects/root/node_modules/peer",
    },
    "extraneous" => Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {},
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/extraneous",
      "name": "extraneous",
      "optional": true,
      "package": Object {
        "name": "extraneous",
        "version": "1.2.3",
      },
      "path": "./node_modules/extraneous",
      "realpath": "/home/user/projects/root/node_modules/extraneous",
    },
    "meta" => Node {
      "children": Map {
        "metameta" => Node {
          "children": Map {},
          "dev": true,
          "devOptional": true,
          "edgesIn": Set {},
          "edgesOut": Map {},
          "error": undefined,
          "extraneous": true,
          "inBundle": false,
          "location": "/meta/metameta",
          "name": "metameta",
          "optional": true,
          "package": Object {
            "name": "metameta",
            "version": "1.2.3",
          },
          "path": "./node_modules/meta/node_modules/metameta",
          "realpath": "/home/user/projects/root/node_modules/prod/node_modules/meta/node_modules/metameta",
          "target": Node {
            "children": Map {},
            "dev": true,
            "devOptional": true,
            "edgesIn": Set {},
            "edgesOut": Map {
              "bundled" => Edge {},
            },
            "error": undefined,
            "extraneous": true,
            "inBundle": false,
            "location": "/",
            "name": "meta",
            "optional": true,
            "package": Object {
              "dependencies": Object {
                "bundled": "",
              },
              "devDependencies": Object {
                "missing": "",
              },
              "name": "meta",
              "version": "1.2.3",
            },
            "path": "./node_modules/meta",
            "realpath": "/home/user/projects/root/node_modules/meta",
          },
        },
      },
      "dev": true,
      "devOptional": true,
      "edgesIn": Set {
        Edge {},
        Edge {},
      },
      "edgesOut": Map {},
      "error": undefined,
      "extraneous": true,
      "inBundle": false,
      "location": "/meta",
      "name": "meta",
      "optional": true,
      "package": Object {
        "name": "meta",
        "version": "2.3.4",
      },
      "path": "./node_modules/meta",
      "realpath": "/home/user/projects/root/node_modules/meta",
    },
  },
  "dev": true,
  "devOptional": true,
  "edgesIn": Set {},
  "edgesOut": Map {
    "optional" => Edge {},
    "overlap" => Edge {},
    "optMissing" => Edge {},
    "prod" => Edge {},
    "bundled" => Edge {},
    "missing" => Edge {},
    "dev" => Edge {},
  },
  "error": undefined,
  "extraneous": true,
  "inBundle": false,
  "location": "/",
  "name": "root",
  "optional": true,
  "package": Object {
    "bundleDependencies": Array [
      "bundled",
    ],
    "dependencies": Object {
      "bundled": "",
      "missing": "",
      "prod": "",
    },
    "devDependencies": Object {
      "dev": "",
      "overlap": "",
    },
    "name": "root",
    "optionalDependencies": Object {
      "optional": "",
      "optMissing": "",
      "overlap": "",
    },
  },
  "path": ".",
  "realpath": "/home/user/projects/root",
}
`
