/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`test/link.js TAP > instantiate with target specified 1`] = `
&ref_1 Link {
  "dev": true,
  "devOptional": true,
  "dummy": false,
  "edgesIn": Set {},
  "edgesOut": Map {},
  "errors": Array [],
  "extraneous": true,
  "fsChildren": Set {},
  "hasShrinkwrap": false,
  "integrity": null,
  "inventory": Inventory {
    "" => &ref_2 Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "dummy": false,
      "edgesIn": Set {},
      "edgesOut": Map {},
      "errors": Array [],
      "extraneous": true,
      "fsChildren": Set {},
      "hasShrinkwrap": false,
      "integrity": null,
      "inventory": Inventory {},
      "legacyPeerDeps": false,
      "linksIn": Set {
        <*ref_1>,
      },
      "location": "",
      "meta": Shrinkwrap {
        "data": Object {
          "dependencies": Object {},
          "lockfileVersion": 2,
          "packages": Object {
            "": Object {
              "name": undefined,
            },
            "../../../../../some/other/path": Object {
              "link": true,
              "resolved": "",
            },
          },
        },
        "filename": null,
        "hiddenLockfile": false,
        "indent": 2,
        "loadedFromDisk": false,
        "loadingError": null,
        "newline": "\\n",
        "path": "/home/user/projects/some/kind/of/path",
        "shrinkwrapOnly": false,
        "tree": <*ref_2>,
        "type": null,
        "yarnLock": null,
      },
      "name": "path",
      "optional": true,
      "path": "/home/user/projects/some/kind/of/path",
      "peer": true,
      "realpath": "/home/user/projects/some/kind/of/path",
      "resolved": null,
      "sourceReference": null,
    },
  },
  "legacyPeerDeps": false,
  "linksIn": Set {},
  "location": "",
  "meta": undefined,
  "name": "path",
  "optional": true,
  "path": "/home/user/some/other/path",
  "peer": true,
  "realpath": "/home/user/projects/some/kind/of/path",
  "sourceReference": null,
}
`

exports[`test/link.js TAP > instantiate without providing target 1`] = `
&ref_1 Link {
  "dev": true,
  "devOptional": true,
  "dummy": false,
  "edgesIn": Set {},
  "edgesOut": Map {},
  "errors": Array [],
  "extraneous": true,
  "fsChildren": Set {},
  "hasShrinkwrap": false,
  "integrity": null,
  "inventory": Inventory {
    "" => &ref_2 Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "dummy": false,
      "edgesIn": Set {},
      "edgesOut": Map {},
      "errors": Array [],
      "extraneous": true,
      "fsChildren": Set {},
      "hasShrinkwrap": false,
      "integrity": null,
      "inventory": Inventory {},
      "legacyPeerDeps": false,
      "linksIn": Set {
        <*ref_1>,
      },
      "location": "",
      "meta": Shrinkwrap {
        "data": Object {
          "dependencies": Object {},
          "lockfileVersion": 2,
          "packages": Object {
            "": Object {
              "extraneous": true,
              "name": "root",
            },
            "../../../../../some/other/path": Object {
              "link": true,
              "resolved": "",
            },
          },
        },
        "filename": null,
        "hiddenLockfile": false,
        "indent": 2,
        "loadedFromDisk": false,
        "loadingError": null,
        "newline": "\\n",
        "path": "/home/user/projects/some/kind/of/path",
        "shrinkwrapOnly": false,
        "tree": <*ref_2>,
        "type": null,
        "yarnLock": null,
      },
      "name": "path",
      "optional": true,
      "path": "/home/user/projects/some/kind/of/path",
      "peer": true,
      "realpath": "/home/user/projects/some/kind/of/path",
      "resolved": null,
      "sourceReference": null,
    },
  },
  "legacyPeerDeps": false,
  "linksIn": Set {},
  "location": "",
  "meta": &ref_3 Shrinkwrap {
    "data": Object {
      "dependencies": Object {},
      "lockfileVersion": 2,
      "packages": Object {
        "": Object {
          "extraneous": true,
          "name": "root",
        },
        "../../../../../some/other/path": Object {
          "link": true,
          "resolved": "",
        },
      },
    },
    "filename": null,
    "hiddenLockfile": false,
    "indent": 2,
    "loadedFromDisk": false,
    "loadingError": null,
    "newline": "\\n",
    "path": "/home/user/projects/some/kind/of/path",
    "shrinkwrapOnly": false,
    "tree": Node {
      "children": Map {},
      "dev": true,
      "devOptional": true,
      "dummy": false,
      "edgesIn": Set {},
      "edgesOut": Map {},
      "errors": Array [],
      "extraneous": true,
      "fsChildren": Set {},
      "hasShrinkwrap": false,
      "integrity": null,
      "inventory": Inventory {},
      "legacyPeerDeps": false,
      "linksIn": Set {
        <*ref_1>,
      },
      "location": "",
      "meta": <*ref_3>,
      "name": "path",
      "optional": true,
      "path": "/home/user/projects/some/kind/of/path",
      "peer": true,
      "realpath": "/home/user/projects/some/kind/of/path",
      "resolved": null,
      "sourceReference": null,
    },
    "type": null,
    "yarnLock": null,
  },
  "name": "path",
  "optional": true,
  "path": "/home/user/some/other/path",
  "peer": true,
  "realpath": "/home/user/projects/some/kind/of/path",
  "sourceReference": null,
}
`
